version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: lab2_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lab2db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234q
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
